<a href="https://colab.research.google.com/github/uzymaru/Tugas3DataMining/blob/main/Tugas3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [13]:
dataset = pd.read_csv('Tugas3.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(x)

[['Rizky' 21.0 2500.0]
 ['Fauzy' 22.0 5000.0]
 ['Andi' 25.0 2340.0]
 ['Rizky' nan 5500.0]
 ['Andi' nan 234500.0]
 [nan 20.0 7600.0]
 ['Rizky' 28.0 1400.0]
 ['Afdan' 30.0 9800.0]
 ['Afdan' nan nan]
 ['Fauzy' 18.0 7500.0]]


In [14]:
print(y)

['Lulus' 'Tidak' 'Tidak' 'Lulus' 'Tidak' 'Lulus' 'Lulus' 'Lulus' 'Tidak'
 'Lulus']


In [20]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy='most_frequent')
imputer.fit(x[:, 0:3])
x[:, 0:3] = imputer.transform(x[:, 0:3])

In [21]:
print(x)

[['Rizky' 21.0 2500.0]
 ['Fauzy' 22.0 5000.0]
 ['Andi' 25.0 2340.0]
 ['Rizky' 18.0 5500.0]
 ['Andi' 18.0 234500.0]
 ['Rizky' 20.0 7600.0]
 ['Rizky' 28.0 1400.0]
 ['Afdan' 30.0 9800.0]
 ['Afdan' 18.0 1400.0]
 ['Fauzy' 18.0 7500.0]]


In [22]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [23]:
print(x)

[[0.0 0.0 0.0 1.0 21.0 2500.0]
 [0.0 0.0 1.0 0.0 22.0 5000.0]
 [0.0 1.0 0.0 0.0 25.0 2340.0]
 [0.0 0.0 0.0 1.0 18.0 5500.0]
 [0.0 1.0 0.0 0.0 18.0 234500.0]
 [0.0 0.0 0.0 1.0 20.0 7600.0]
 [0.0 0.0 0.0 1.0 28.0 1400.0]
 [1.0 0.0 0.0 0.0 30.0 9800.0]
 [1.0 0.0 0.0 0.0 18.0 1400.0]
 [0.0 0.0 1.0 0.0 18.0 7500.0]]


In [15]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [16]:
print(y)

[0 1 1 0 1 0 0 0 1 0]


In [24]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state=1)

In [25]:
print(x_train)

[[0.0 0.0 0.0 1.0 28.0 1400.0]
 [0.0 1.0 0.0 0.0 18.0 234500.0]
 [0.0 0.0 0.0 1.0 21.0 2500.0]
 [0.0 0.0 0.0 1.0 18.0 5500.0]
 [0.0 0.0 1.0 0.0 22.0 5000.0]
 [1.0 0.0 0.0 0.0 30.0 9800.0]
 [1.0 0.0 0.0 0.0 18.0 1400.0]
 [0.0 0.0 0.0 1.0 20.0 7600.0]]


In [26]:
print(x_test)

[[0.0 1.0 0.0 0.0 25.0 2340.0]
 [0.0 0.0 1.0 0.0 18.0 7500.0]]


In [27]:
print(y_train)

[0 1 0 0 1 0 1 0]


In [28]:
print(y_test)

[1 0]


In [29]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [30]:
print(x_train)

[[0.0 0.0 0.0 1.0 1.4011442584664595 -0.4216762966826798]
 [0.0 1.0 0.0 -1.0 -0.8864382043359234 2.643984358498066]
 [0.0 0.0 0.0 1.0 -0.2001634654952085 -0.4072094295840148]
 [0.0 0.0 0.0 1.0 -0.8864382043359234 -0.3677543374967465]
 [0.0 0.0 1.0 -1.0 0.028594780785029784 -0.3743301861779579]
 [1.0 0.0 0.0 -1.0 1.858660751026936 -0.31120203883832864]
 [1.0 0.0 0.0 -1.0 -0.8864382043359234 -0.4216762966826798]
 [0.0 0.0 0.0 1.0 -0.42892171177544675 -0.3401357730356587]]


In [31]:
print(x_test)

[[0.0 1.0 0.0 -1.0 0.7148695196257446 -0.40931370116200244]
 [0.0 0.0 1.0 -1.0 -0.8864382043359234 -0.34145094277190097]]
